version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
    timezone: Europe/Helsinki
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phpseclib/phpseclib
    versions:
    - 2.0.31
  - dependency-name: phan/phan
    versions:
    - 4.0.1
    - 4.0.3
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.13
    - 8.5.14
  - dependency-name: filp/whoops
    versions:
    - 2.9.1
    - 2.9.2
  - dependency-name: symfony/http-foundation
    versions:
    - 4.4.18
    - 4.4.19
  - dependency-name: symfony/http-kernel
    versions:
    - 4.4.18
    - 4.4.19
  - dependency-name: fzaninotto/faker
    versions:
    - 1.9.2
  - dependency-name: doctrine/dbal
    versions:
    - 2.10.4
  - dependency-name: fideloper/proxy
    versions:
    - 4.4.0
  - dependency-name: barryvdh/laravel-cors
    versions:
    - 2.0.1
  - dependency-name: barryvdh/laravel-ide-helper
    versions:
    - 2.7.0
  - dependency-name: laravel/framework
    versions:
    - 5.8.38
  - dependency-name: laravel/passport
    versions:
    - 7.5.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
    timezone: Europe/Helsinki
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.0
    - 1.32.5
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: puppeteer
    versions:
    - 5.5.0
  - dependency-name: bootstrap
    versions:
    - 4.5.3
  - dependency-name: elliptic
    versions:
    - 6.5.3
