version: "3.1"
services:

    web:
        build:
            dockerfile: ./docker/nginx/Dockerfile
            context: .
        container_name: onnidb-web
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "${WEB_PORT:-8080}:80"
        depends_on:
            - php-fpm

    php-fpm:
        build:
            dockerfile: ./docker/php-fpm/Dockerfile
            context: .
        container_name: onnidb-php
        env_file: .dev.php.env
        volumes:
            - ./storage:/usr/share/onnidb/storage:rw
            - ./database.sqlite:/usr/share/onnidb/database/database.sqlite

    redis:
        image: redis
        container_name: onnidb-redis
        ports:
            - 6380:6379
